// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwajnjrojryebgcesebe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3YWpuanJvanJ5ZWJnY2VzZWJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODUxNzMsImV4cCI6MjA2NTA2MTE3M30.iPHCrdtwFHQyI1ZdZtb_mZ3YZ7UondFUN7UsgODsRLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);